### ISSUE TITLE
Build official docs in own action workflow

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#1004]
I think the official docs get currently build inside a test case via pytest.
This makes it hard to see quickly any warnings.

We have a "Docs CI" pipeline, but this only contains the linkcheck. We should also add a doc-build there.

**Comment by chrisjsewell** [comment]
Heya, yes after finishing the docs fixes, I was going to add https://docs.readthedocs.io/en/stable/pull-requests.html
