### ISSUE TITLE
Bug: global_options can't set constraints

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#1010]
When constraints shall be set via `needs_global_options`, only the first character of the constraints-name is taken as name and an error message gets shown that this "name" is not defined inside needs_constraints.

Example:
```python
needs_constraints = {
    "team": {
        "check_0": "author == \"Bob\"",
        "severity": "LOW"
    },
}

needs_global_options = {
      'constraints': 'team', 'type == "req" '
}
```

In the above case, we get an error message like: ``Constraint t of need id REQ_123 is not allowed by config value 'needs_constraints'.`` (notice the single "t").

Idea: Maybe setting `team,` (comma at the end) would help, so that it gets recognized as a list (untested)

**Comment by chrisjsewell** [comment]
Heya @danwos I can't reproduce this (see #1026).
Can you provide the rST file used, or propose change to my PR cheers

**Comment by BanupriyaVenk** [comment]
Second Example/Issue:

needs_constraints = {
    "team": {
        "check_0": "author == \"Bob\"",
        "severity": "LOW"
    },
}

needs_global_options = {
      'constraints': 't', 'status == "accepted"', 'type == "req" ',
}

In the above case as well, we get an error message like: Constraint t of need id REQ_123 is not allowed by config value 'needs_constraints'. (notice the single "t").

**Comment by chrisjsewell** [comment]
Update, the bug is in `_merge_global_options`, working on it now

**Comment by chrisjsewell** [comment]
> Idea: Maybe setting team, (comma at the end) would help, so that it gets recognized as a list (untested)

Yes this is the case @BanupriyaVenk : the value for `contraints` is expected to be a list of strings: https://github.com/useblocks/sphinx-needs/blob/0954a50847ddecffef3edb6ae96f9e255b713453/sphinx_needs/data.py#L161

So the simple resolution here, would be to close as the "user's fault" 😅 

But ideally, there would be some form of checking for "value correctness", against known need's keys

**Comment by chrisjsewell** [comment]
@danwos perhaps we close this, and open an "enhancement" issue, for checking global option values types, and providing better user feedback on errors?

**Comment by danwos** [comment]
I'm not 100% sure, for me, it is still a bug. A "," should not be needed, even if the value shall be list of  strings.
I mean `links`, `tags` and co are all taking a list, but there is no need to end a single element with a ",".
So I think the constraints function, should check if one of `,;` is in the string, if not `value = [value]` and then go on.

What do you think?

**Comment by chrisjsewell** [comment]
>  A "," should not be needed, even if the value shall be list of strings.

@danwos This seems to assume that the value should always be a string, which should then apply a transform to, to get the processed value, i.e. how directive options?

The main problem here is, I feel, is that `_merge_global_options` does not have a field specific functionality like this; you have to give it the "final" processed value, which is not necessarily the same as how you would give it in the directive option

**Comment by danwos** [comment]
You are right, we can't do it in `_merge_global_options`.
So a generic check makes sense, which is out of the specific scope of this ticket.

So yes, just add a "," :)

**Comment by chrisjsewell** [comment]
> So yes, just add a ","

So you want to add logic in `_merge_global_options`, to convert any string ending in `,` to a list of strings?

**Comment by danwos** [comment]
No, I thought in the given config the problem is just a missing `,`, so this can be added.
```
needs_global_options = {
'constraints': 's,', 'rb_as_status == "accepted"', 'type == "req" '  # added "," in "s,"
}
```
Or have I missed something?

**Comment by chrisjsewell** [comment]
> Or have I missed something?

there is no logic currently, to turn `'s,'` into `["s"]`, which is what it needs to be (a list of strings)

**Comment by danwos** [comment]
So the way to go is to use a configuration like this for `needs_global_options`:
```
needs_global_options = {
   'constraints': [
       ( ['check_1', 'check_2'], 'status == "accepted" '),
       ( ['check_3'], 'status == "closed" ')
   ]
}
```

The current solution has one limitation: If the filter of 2 global_options-defintions matches, the later will overwrite the first set constraints. There is currently no way to combine both results into a common value for `constraints` option.
