### ISSUE TITLE
Sphinx-Needs throws exception when "." is used in ID

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-needs#1096]
Sphinx-Needs throws a cryptic python error 

> Extension error (sphinx_needs.directives.need):
Handler <function process_need_nodes at 0x7fc668dc98a0> for event 'doctree-resolved' threw an exception (exception: too many values to unpack (expected 2))

if "." is used in an ID after configuring a regex as follows in `conf.py`

> needs_id_regex = r'.*'

Although it is not a good idea to use "." in IDs, Sphinx-Needs should be robust with such a case.

Related Issue: https://github.com/useblocks/sphinx-needs/issues/852

**Comment by danwos** [comment]
I agree, there is a missing check for handling need_parts.

Short reminder: `.` is used to reference a need_part inside a need, e.g. `REQ_123.SECTION_X`.
It is generally not allowed by Sphinx-Needs to use a `.` in an ID, as the ID gets split by `.`.

In your case the returned value for the need_part is `None` or `""`, which is not detected and handled correctly.

**Comment by Rubyfi** [comment]
I have the same issue, but it surfaces when an invalid link is provided, e.g.:
`:derives: This derives...`
Here's a stacktrace:
```
Traceback (most recent call last):
  File "...\sphinx\events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "...\sphinx_needs\directives\need.py", line 403, in process_need_nodes
    post_process_needs_data(app)
  File "...\sphinx_needs\debug.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "...\sphinx_needs\directives\need.py", line 379, in post_process_needs_data
    check_links(needs, needs_config)
  File "...\sphinx_needs\directives\need.py", line 448, in check_links
    need_id, need_part_id = link.split(".")
ValueError: too many values to unpack (expected 2)
```
