### ISSUE TITLE
needs_id_regex should not apply on needs_external_needs

### ISSUE THREAD

**Issue by David-Le-Nir** [useblocks/sphinx-needs#1099]
When using _needs_id_regex_ and when referencing external documents via _needs_external_needs_ the regex is checked against all "remote" needs.

Would it be possible to only check the regex for the "local" document ?

For my users, each document should have its own regex for their own needs. Then when they refer to other documents, the regex check fails.

I agree with my users that the expected behaviour of the _needs_id_regex_ should to only apply locally because else every documents have to use the same regex.

I guess including _is_external_ value in the [regex check](https://github.com/useblocks/sphinx-needs/blob/73b961e29583bc0ac8892ef9c4e2bfb75f7f46bb/sphinx_needs/api/need.py#L193) would not be too hard. The questions are:

- how to make this behaviour optional, like a new option _need_id_regex_local_only_ 
- and what would be its default value

If you agree on this, I can make the PR if you want.

**Comment by danwos** [comment]
Ohh, that's an interesting bug, and thanks for reporting it.

I agree that the external_needs should not be checked by the regex.
So I don't even need an option to configure this, I would just deactivate it completely for external_needs.

I see no use case, why the needs of project A should be checked by rules in project B.

Will be happy to merge an upcoming PR.
