### ISSUE TITLE
Output shows has_dead_links=True on missing links

### ISSUE THREAD

**Issue by revati-naik** [useblocks/sphinx-needs#1149]
I have a setting in the `confy.py` file

```
needs_extra_links = [
   {
      "option": "links",
      "incoming": "links incoming",
      "outgoing": "links outgoing",
      "copy": False,
      "allow_dead_links": True,
      "style": "#ffcc00",
      "style_part": "dotted,#00AA00",
   }
]
```

According to [this](https://sphinx-needs.readthedocs.io/en/latest/configuration.html#needs-extra-links) document, adding the above should allow dead links.

However, I still see the warning in the logs. Additionally, I see `has_dead_links: True` in the output.

Her is a sample rst file

```
.. swrq:: Ttile
    :id: SWRQ_PACKAGE_1
    :integrity: QM
    :links: SWRQ_PR_28, ARCH_PACKAGE_2
    
```

Out of the links mentioned, `SWRQ_PR_28` is a dead link.

In the output, I see

```
<a id="SWRQ_LOGGING_41"></a>

| Software Requirement: **Ttile** [SWRQ_PACKAGE_1](#SWRQ_PACKAGE_1)<br/>   |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| integrity: QM<br/>has_dead_links: True<br/><br/>links outgoing: SWRQ_PR_28, [ARCH_PACKAGE_2](../../arch/arch_package_2.md#ARCH_PACKAGE_2)<br/><br/>                                          |
|                                                                                                                                                                                              |

```

I hoped to not see `has_dead_links` in the table.

**Comment by danwos** [comment]
You will always get a log message about the dead link. The difference is the log-level, which is moved from `Warning` down to `Info` and therefore may not stop the build.
Is it really still a `Warning` in your log?

Regarding the `has_dead_links` output in the need itself, I'm afraid that you have to create [your own layout](https://sphinx-needs.readthedocs.io/en/latest/layout_styles.html#defining-own-layouts) to remove it.

**Comment by revati-naik** [comment]
@danwos Thanks for confirming this.

**Comment by revati-naik** [comment]
> Is it really still a `Warning` in your log?

No it isnt.

**Comment by danwos** [comment]
In this case I close the issue, as Sphinx-Needs behaves as documented.

Feel free to reopen, if I missed something.
