### ISSUE TITLE
list-table directive is not supported within a need

### ISSUE THREAD

**Issue by revati-naik** [useblocks/sphinx-needs#1161]
I am using the following extensions to build my documentation with sphinx

- Sphinx v7.0.1
- Sphinx-needs v1.2.2
- sphinx-makrdown-buidler v0.6.6
- sphinx-rtd-theme v1.3.0
When I try to have a table inside of the needs as shown below, the markdown builder does not format the table correctly for it to render.

```
======================
Test Image With Target
======================

.. image:: /static/markdown.png
   :target: https://github.com/liran-funaro/sphinx-markdown-builder

Download :download:`this example image </static/markdown.png>`.

.. req:: Some requirement
   :id: REQ_1

  .. list-table::
     :header-rows: 1
     :class: tight-table
  
     * - #
       - Action
       - Expected Result
       - Notes
       - Result
     * - 1
       - Start
       - Test should Start
       - More Notes
       - No result
```
The same works fine with the HTML builder.

Do I need to do something different for the markdown builder? How can I fix this?

EDIT:

I performed some tests in sphinx-markdown-builder to see how I can use the `.. list-table::` in the `.rst` file. I tried it in two different approaches.

1. I had the `.. list-table::` nested in one of the needs. I have attached the diff patch - 
[test_nested_list_table.PATCH](https://github.com/useblocks/sphinx-needs/files/14829076/test_nested_list_table.PATCH)
 and the markdown file: 
[image-target.md](https://github.com/useblocks/sphinx-needs/files/14829084/image-target.md)

2. I had the `.. list-table::` as an independent entity in the file (non-nested):

 
[test_list_table.PATCH](https://github.com/useblocks/sphinx-needs/files/14829098/test_list_table.PATCH)
and the markdown file:

[image-target.md](https://github.com/useblocks/sphinx-needs/files/14829102/image-target.md)

This time I see the right table format.

**Comment by danwos** [comment]
Thanks for reporting the bug. :+1: 

Like for #1162, I'm afraid that this problem is more related to `sphinx-markdown-builder`, which maybe does not support nested directives.

As long our code follows the rst-standards and works with `html`, `latex` and `simplepdf`, I see the bug in the used builder.

I close this issue, but feel free to reopen, if you have a different opinion :)
