### ISSUE TITLE
Option to save the generated image a a relative path

### ISSUE THREAD

**Issue by revati-naik** [useblocks/sphinx-needs#1162]
I am using the `sphinx-markdown-builder` and in the output markdown file, I see the tag for needpie. However, the path to the image file is absolute. Can we instead have a relative path?

Can we set the path to save the image via a tag in `needpie`?

The output I see is 

```
![image](/home/firstname.lastname/some/path/need_pie.png
```

**Comment by danwos** [comment]
I'm not sure if we can do here much, as `needpie` is generating relative paths for the default builders like `html`. So from my point of view the functions works as expected.
And I can't say, why this is not working with `sphinx-markdown-builder`.

Maybe someone can help here and knows some internal details about `sphinx-markdown-builder`.

**Comment by chrisjsewell** [comment]
heya, closing this, since it is not supported in sphinx, I'm afraid it will not be supported in sphinx-needs
