### ISSUE TITLE
Warnings in Sphinx-Needs demo

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-needs#1211]
I was trying out the [Sphinx-Needs demo](https://sphinx-needs-demo.readthedocs.io/en/latest/) on Gitpod and the found that a clean build always throws these warnings.
![image](https://github.com/user-attachments/assets/36a6cdfc-3ff7-46eb-bbe4-bc7a3e408752)

![image](https://github.com/user-attachments/assets/607bcff7-8903-4a9f-a706-cdec13c9a739)

Would be nice if these are checked and fixed.

**Comment by twodrops** [comment]
Additionally, some hints in `Readme.md` would be nice for a newbie on how to use the sandbox. For example, 

```
cd docs/
make html
```

**Comment by chrisjsewell** [comment]
Heya, this should be opened on https://github.com/useblocks/sphinx-needs-demo,
but anyhow there is a new https://sphinx-needs.readthedocs.io/en/latest/tutorial.html in the docs here that replicates some of them docs 😄
