### ISSUE TITLE
needs_warnings shall support user defined filter code function with all needs as parameter 

### ISSUE THREAD

**Issue by PhilipPartsch** [useblocks/sphinx-needs#1238]
It is useful to have access to all `needs` for implementing warning scripts which even cover linked needs.
Like in [needs_warnings](https://sphinx-needs.readthedocs.io/en/latest/configuration.html#needs-warnings) and extended with needs. Example: `def my_custom_warning_check(need, log, needs)`

**Comment by chrisjsewell** [comment]
folding this into #1322
