### ISSUE TITLE
dynamic function not resolved in 'description' key in needs.json

### ISSUE THREAD

**Issue by brandtnerfabian** [useblocks/sphinx-needs#1289]
I defined a need like this:
```
.. testneed:: This is a test
    :id: PT_TEST
    :value: ""

    **[[copy("value")]]**
```

I then used a needextend like this:
```
.. needextend:: id == "PT_TEST"
    :value: this is a test value
```

Now when i build a json file, the description is displayed like this:
`"description": "**[[copy(\"value\")]]**"`

Shouldn't the description say "this is a test value" and not just display the copy function?

**Comment by brandtnerfabian** [comment]
Alright, thanks for the info

**Comment by chrisjsewell** [comment]
Ok I will close this for now then, but bear in mind the feedback thanks
