### ISSUE TITLE
Duplicated Ids no longer fail the build

### ISSUE THREAD

**Issue by aanagnosastronauticscom** [useblocks/sphinx-needs#1291]
The update from the 2.X series to the 3.X looks to have had some unintended impact to an undocumented feature that was rather convenient for my use case.

Some work was done to [needs.py](https://github.com/useblocks/sphinx-needs/commit/ff4ae90378952c673945c7a6a8eb3b4eb0070183) to resolve detecting duplicated ids in parallel builds and as part of that the raising of an exception when a duplicated id is found was removed.

The current 3.X series still detects the duplicated ids, but will continue the build and even exit with a status of 0 (success).
In the 2.X series, because of raising that exception, you would get an error status of != 0 (2 actually) which i was able to use to fail CI pipelines.

There is still the base sphinx option of treating all warnings as errors to return the functionality, but that has the side effect of failing things when expected warnings are being triggered, which is not exactly ideal.

I personally think a duplicate id should be a fatal error not a warning, it leads to undefined and missing output data.
However at least having a flag to elevate this warning to fatal error would be appreciated.

**Comment by chrisjsewell** [comment]
> but that has the side effect of failing things when expected warnings are being triggered

heya, you should be using https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-suppress_warnings for expected warnings

this will not be changing I'm afraid; all sphinx parsing should be fault-tolerant by default, and sphinx_needs provide clear warning type/subtypes to fine-grain control of these warnings.

If you wish for any other functionality, I would suggest opening an issue/discussion on sphinx core
