### ISSUE TITLE
Regression on title usage in need body

### ISSUE THREAD

**Issue by adegroote** [useblocks/sphinx-needs#1336]
```
.. need:: Test with title
   :id: FOO_1234

   Title
   *****

   xxx
```

The following snippet works with at least sphinx_needs 2.0.0, but not anymore in sphinx_needs 4.0.0. It fails with 

```
CRITICAL: Unexpected section title.
```

Is it expected or just a regression ?

**Comment by chrisjsewell** [comment]
Heya, yes it is expected:
it did not warn in v2, but that did not mean it worked since nested headings are fundamentally incompatible with the sphinx/docutils documentation model: https://gist.github.com/chrisjsewell/0c5827add50074fef0937e2543e955b4

**Comment by adegroote** [comment]
Thanks you for the answer.  I will update our documents accordingly so (and probably try to fix place where we use internally `nested_parse_with_tiles`.
