### ISSUE TITLE
Empty result list for needflow throws plantuml error

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#159]
If the result list is empty, the generated code contains errors for plantuml.

Looks like plantuml doesn't like comments only.

Will throw error:
```
@startuml

' Single comment

@enduml
```

All good:
```
@startuml

' Single comment
a --> b

@enduml
```

But solution would be to fix it on plantuml side.

**Comment by chrisjsewell** [comment]
perhaps this was implemented previously, but empty result lists no longer output a plantuml graph: https://github.com/useblocks/sphinx-needs/blob/cc7f9a6a96203b7655afb8e54ff8006b5226784a/sphinx_needs/directives/needflow/_plantuml.py#L371-L374

so gonna close, but feel free to re-open if this is not the case
