### ISSUE TITLE
set title for links

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#30]
If links are shown inside a need, it would be great if the link title is set and its content is the linked need title text.

This would make it a little bit easier to know, which need is behind a presented link-id.

**Comment by PhilipPartsch** [comment]
@danwos : I belive this is already been implemented with [needs-show-link-title](https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-show-link-title) and [needref](https://sphinxcontrib-needs.readthedocs.io/en/latest/roles.html#need).
