### ISSUE TITLE
Incremental build support

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#354]
Currently an incremental build is not really supported when using Sphinx-Needs.
It is possible to perform it, but the result may not be valid.

Reason: A need in file A may be represented by a needtable in file B.
Then the need gets updated and only file A gets build. File B stays untouched and shows the old data of the need.

There are also some issues, where it looks like that an incremental build gets deactivated when using certain Sphinx-Needs functions.

However, an incremental build is important for developers, to get a fast feedback of their changes.

There are two problems to solve:
1. To know which files needs to be rebuild, if certain files get updated.
2. Let Sphinx know, that other files need to be rebuild as well (I think there is an event for this)

### Dependency graph
During a full-build, Sphinx-Needs could create a dependency graph to know which needs got represented in which files.
If a need got update, Sphinx-Needs would know which files rebuild as well.

Drawback: If need was not part of a needtable (in another file), but got updated and would be now part of it, there is now way to know that this needtable/files needs to be rerenderd as well.

### Fix page rebuild
Sphinx-Needs could always rebuild **all** pages, which are having needtable, needflow, neeflow, ....

Drawbacks:
- needs, which get there option value via a dynamic function from another need, get not updated, if on there page is no needtable 
- May still build a lot of pages, which could take a looooong time.

### ?
Some other magic...

Okay, have to thing about this even more.
So issue is just a placeholder....

**Comment by Thomas-Swindells-t** [comment]
One thing that might help is to refactor out filtering to be its own citizen.
Each filter expression and its result set would be stored as part of the build output. The relationship between a user of the filter (needtable, needflow etc) would be recorded (with deduplication being done on reused filter expressions).

A partial build would then check to see if any node definitions are changed/added/removed. If any are then all the filter expressions are rerun. If the results of a filter expression changes then the pages that are linked to the filter expression could then be marked for rebuilding.

**Comment by danwos** [comment]
I close this one, as implementation is really complex and a lot of other stuff is more important.

**Comment by tonyarkles** [comment]
I did get burned by this today (new user, haven't figured out the sharp edges yet). I have a `needflow` in a separate document and it wouldn't get updated unless I either changed that specific file or did `make clean html`.

**Comment by twodrops** [comment]
This will hit everyone at some time or the other ;)

We need to decide for what usecases incremental behaviour shall be used.

- As a quick feedback to users who do a local build: I guess the current incremental build can be used for this with its limitation that the overall documentation might not be consistent, but usecases like preview etc, for currently edited document will work.

- In pipelines for performance optimization: For this usecase, one should not use the incremental build and should always go for full build. Performance of pipelines should be optimized with other means,

As @danwos mentioned, a fully robust incremental build for sphinx-needs will be extremely hard to implement and may not be worth the benefits it shall bring.
