### ISSUE TITLE
Table needs id

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#434]
``sphinxcontrib-needs/docs/directives/needtable.rst:4: WARNING: Any IDs not assigned for table node``

With version 0.7.4 normal tables get wrapped inside a container/div.
In this case the generated docutils id goes to the container and not to the table.

This seems to make problems. Maybe we should just generate a dummy-id or set an id.

**Comment by arwedus** [comment]
I see the same WARNING. Does this have any impact or is it safe to ignore?

**Comment by danwos** [comment]
It should be safe to ignore. Table Ids are not needed by sphinx-needs. Only docutils asks for it.

**Comment by arwedus** [comment]
btw.: The warning happens when you add a title to the needtable. Without a title, there's no warning.
