### ISSUE TITLE
needs_string_links and need_extra_options

### ISSUE THREAD

**Issue by adegroote** [useblocks/sphinx-needs#545]
It is not very clear from the documentation that one needs to add an extra entry in `need_extra_options` to have `need_string_links` works properly. Maybe it would be nice to have a cross-check that options referenced in `needs_string_links` needs to explictly exists in `need_extra_options`. Or at least, document it more explicitly.

**Comment by danwos** [comment]
Good point, the documentation and especially a check for this is missing.

Thanks for reporting this. :+1:

**Comment by danwos** [comment]
It got documented. Thanks for the report.
