### ISSUE TITLE
IDE: :id: not working anymore?

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#602]
It looks like the autocompletion for `:id:` does not work anymore.

No ID is provided. For example:
```rst
.. req: My req
   :id:   <-- After the last ":" an id should be provided.
```

![image](https://user-images.githubusercontent.com/998700/172855829-a75ff53c-fe70-4741-acd5-63a90d7fa001.png)

**Comment by haiyangToAI** [comment]
That's wired. It works for me. I will look into it.

![Screenshot_2022-06-09_15-25-45](https://user-images.githubusercontent.com/30159983/172859008-504a3bfa-c4ee-4c95-9b28-a2071d06c6dd.png)

**Comment by haiyangToAI** [comment]
@danwos Yes, I think it can be closed.
