### ISSUE TITLE
Analysis of needs metrics

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#631]
Idea by @StephanKuempel

We already have ``.. needreport`` to document the current configuration.

But it would be also good to document various aspects of the current need-data (dict).

Ideas, what shall be documented (only the numbers, no list of needs):
* Needs amount
* Used need types
* Needs per type
* Used options
* Used options per type (`Req` --> `author`, `status`, `Spec` --> `tags`)
* Used link types
* Amount of needs per link types
* Target need type of links per link type (E.g. `validates` --> `Req`, `Test`, `block` --> `Spec`)

This analysis can be also done on a ``needs.json`` file.

Example:
```rst
.. needreport::
   :usage:
```

**Comment by chrisjsewell** [comment]
closed in #684
