### ISSUE TITLE
Activity diagram throws error inside needuml directive

### ISSUE THREAD

**Issue by MohSam1** [useblocks/sphinx-needs#649]
There are syntax errors when activity diagram is realized inside a needuml directive. Below is the code and the corresponding error.

``` rst

.. needuml::

    start
    :Some Action;
    :Some Other Action;
    note 
    hello welcome to Note
    these are multi line!!
    endnote
    end
```

**WARNING: error while running plantuml
b'ERROR\r\n3\r\nSyntax Error?\r\nSome diagram description contains errors\r\n'**

**Comment by haiyangToAI** [comment]
Hi @MohSam1,

Thanks for reporting this.

The problem is `allowmixing`. For  directive `needuml`, it has `allowmixing` configured by default. But this syntax `allowmixing` is not allowed for activity diagram.

Will fix it soon.
