### ISSUE TITLE
needextract seems broken with requirement containing need_parts

### ISSUE THREAD

**Issue by adegroote** [useblocks/sphinx-needs#651]
It throws on 

```
  File "/usr/local/lib/python3.9/site-packages/sphinxcontrib/needs/layout.py", line 40, in create_need
    raise SphinxNeedLayoutException(f"Given need id {need_id} does not exist.")
sphinxcontrib.needs.layout.SphinxNeedLayoutException: Given need id 163 does not exist.
```
where 163 is the generated id of the parts.

**Comment by haiyangToAI** [comment]
Hi @adegroote,

From the error message above you can see, there is nothing to do with [needextract](https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needextract.html#needextract).

The issue is you want to call function `create_need()`, which needs parameter `need_id`, but you passed a `need_part id`. 

Be aware, [need_part](https://sphinxcontrib-needs.readthedocs.io/en/latest/roles.html#need-part-np) is not a [need](https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/need.html#need-req-or-any-other-defined-need-type) object. `need_part id` is not `need_id`.  You can't create `need node` for `need_part`.

**Comment by adegroote** [comment]
Well, the "full" backtrace is

```
  File "/usr/local/lib/python3.9/site-packages/sphinx/cmd/build.py", line 294, in main
    return build_main(argv)
  File "/usr/local/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.9/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/usr/local/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 529, in write
    self._write_parallel(sorted(docnames),
  File "/usr/local/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 566, in _write_parallel
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python3.9/site-packages/sphinx/environment/__init__.py", line 535, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/usr/local/lib/python3.9/site-packages/sphinx/environment/__init__.py", line 586, in apply_post_transforms
    self.events.emit('doctree-resolved', doctree, docname)
  File "/usr/local/lib/python3.9/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/local/lib/python3.9/site-packages/sphinxcontrib/needs/directives/needextract.py", line 88, in process_needextract
    need_extract = create_need(
  File "/usr/local/lib/python3.9/site-packages/sphinxcontrib/needs/layout.py", line 40, in create_need
    raise SphinxNeedLayoutException(f"Given need id {need_id} does not exist.")
sphinxcontrib.needs.layout.SphinxNeedLayoutException: Given need id 163 does not exist
```

so it is definitively related to need_extract (but yes, sorry for the "shortned" backtrace

**Comment by haiyangToAI** [comment]
Sure, it can start from `needextract`, but when you follow the trace, you can see the **real issue** is function `create_need()`. 

Again, `need_part id` is **not** `need_id`. In you case, the message says: `Given need id 163 does not exist`. Surely `163` does not exist, it's a `need_part id`, **not** a `need_id`.

**Comment by danwos** [comment]
I'm somehow lost, as I don't have a reproducible example here. I have the feeling both of you have something different in mind ;)

So I guess the following does not work?
```rst
.. req:: Test me
   :id: REQ_001
   
   :np:`This is a  need part`
   
.. needextract:: REQ_001
```

Or is the scenario even more complex?

**Comment by adegroote** [comment]
@danwos yes exactly. If you are not able to reproduce it, I would try to create an example on my side. The problem still exists in 1.0.1.

**Comment by danwos** [comment]
@adegroote No it's fine. Now we know what to look for and can reproduce it :)

**Comment by haiyangToAI** [comment]
@danwos well, I tried the example above, I don't see a problem and it works for me.

I still feel something not related to `needextract` went wrong. Based on the error message from @adegroote, it seems to me in `layout.py` function `create_need()` is the issue. Just my thoughts.

**Comment by danwos** [comment]
AS the content gets copied, also the need_part definition is copied.
So I guess during handling of this copy, something strange happens.
I agree, that this problem may exist in the layout.py file.

So we really need an example, which reproduces this error.

@adegroote Just to be sure, you really mean need_part not embedded needs?

**Comment by adegroote** [comment]
The following example reproduces my issue:

```
.. need:: Foo Bar
   :id: FOO_00001
   :tags: foo, bar

    xxx
        - :np:`1 foo` foo bar


.. needextract:: 
   :tags: foo
```

**Comment by haiyangToAI** [comment]
Now I see the issue. The issue is coming from the definition of need_part. 

For instance, in the example above, the need_part is defined like this: :np:`1 foo` foo bar. The issue is the content `foo bar` after :np:`1 foo`. Somehow the content makes the need_part doing something wired. I will look into the `need_part`, see how it handles the content there.

Thanks @adegroote for this unique use case.
