### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by RedX2501** [useblocks/sphinx-needs#664]
Hello,

~Where is the changelog for each released version?~

~How do I know whether I should upgrade or not?~

Ok, I found it on the home page. It's very odd that there is no link on the release pages.

**Comment by danwos** [comment]
Just to be sure, what do you mean with the release page?
The one provided by github itself or something else?

**Comment by RedX2501** [comment]
Hi, I mean this page https://github.com/useblocks/sphinx-needs/tags
compare it for example with https://github.com/microsoft/vscode/releases

As I collect the links I just noticed that the page that is available is actually the "tags" page and that you have nothing under releases.

I guess the only way would be to have a commit message on the tag with a link to the changelog. Not sure if that is reasonable though.

So it's confusing but consistent.
