### ISSUE TITLE
Support for Sphinx Book Theme

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-needs#683]
The [Book Theme](https://sphinx-book-theme.readthedocs.io/en/stable/index.html) is a well maintained Sphinx-Theme in comparision to the popular [Sphinx RTD Theme](https://github.com/readthedocs/sphinx_rtd_theme). ([66 open PRs](https://github.com/readthedocs/sphinx_rtd_theme/pulls) as on 05.09.2022).

Similar to the RTD Theme, the Book Theme does not work with Sphinx-Needs 1.0.1+ because of doc-utils problem, which hopefully will be fixed by them soon. An [issue](https://github.com/executablebooks/sphinx-book-theme/issues/592) exists for this already.

The Book Theme however has some issues with Sphinx-Needs 0.7.9 and this problem would probably exist even when the docutils issue above is solved. So as a preparation, these issues needs to be solved.

![image](https://user-images.githubusercontent.com/103930/188395760-7be85b38-a6a2-4b34-871b-354a56e9b894.png)

1. The rendering of Sphinx-Needs with Book Theme is not ideal. Grey Needs Layout (Alabaster like) which does not go well with the overall Book Theme look and feel.
2. The Collapse/Expand Button is missing.

Needs-Table rendering works pretty good with Sphinx Book Theme.

**Comment by danwos** [comment]
This should be checked also the https://pydata-sphinx-theme.readthedocs.io/en/stable/ theme.

However, changing the common need-style is CSS work.
We can't change it in general, as then it would maybe not fit other themes anymore.

But we have this concept of need-themes, by default, `modern`, `blank`, and `dark` are available.
https://pydata-sphinx-theme.readthedocs.io/en/stable/
Maybe one of them is already working.
For sure we could add a fourth one, which fits best for book/pydata theme.

**Comment by twodrops** [comment]
ah, sorry I completely forgot about https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-css
Therefore it makes sense to leave it to the user to customize it to match the theme used. We could close this.
Thanks for the hint.
