### ISSUE TITLE
needuml keys are shown in meta data

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#687]
This
```rst
.. comp:: Component Y
   :id: COMP_002

   .. needuml::
      :key: sequence

      Alice -> Bob: Hi Bob
      Bob --> Alice: Hi Alice
```
shows a sequence option in the need:
![image](https://user-images.githubusercontent.com/998700/189335515-6f6f3a66-1843-4158-b33a-78c7e90b9d8a.png)
This can be seen also in our [docs](https://sphinx-needs.readthedocs.io/en/latest/directives/needuml.html#COMP_002)

Not sure,why an option gets created, as the plantuml code should be in a single dict-container under the need.

**Comment by PhilipPartsch** [comment]
I expect the seen behaviour, maybe it shall be better  [documented](https://sphinx-needs.readthedocs.io/en/latest/directives/needuml.html#key).
If we want to save something, it has to be  defined as e[extra option](https://sphinx-needs.readthedocs.io/en/latest/configuration.html#needs-extra-options) .
It is possible to remove options with the might full layout functionality [layout functionality ](https://sphinx-needs.readthedocs.io/en/latest/layout_styles.html#defining-own-layouts) .
So I vote for, keep it as it is.
