### ISSUE TITLE
Custom jinja context

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#704]
There shall be a config option like html_context, which allows defining custom content to jinja.

This is already done for filter string, but we need it also for :
* Templates
* string-links
* Other functions, where Jinja is used.

**Comment by twodrops** [comment]
@danwos Thanks for creating this issue as discussed. Please check if you can provide a detailed page on Jinja support in Sphinx-Needs as part of this issue or this one https://github.com/useblocks/sphinx-needs/issues/604#issuecomment-1152239751
