### ISSUE TITLE
needuml vs plantuml C4

### ISSUE THREAD

**Issue by AlexanderLanin** [useblocks/sphinx-needs#707]
# Expected behavior
This block is rendered:
```
.. needuml::

    !include <C4/C4_Container>

    Container(c1, "Container 1")
    Container(c2, "Container 2")

    Rel(c1, c2, "uses")
```

# Actual behavior
`ERROR\n1030\nSyntax Error?\nSome diagram description contains errors`

# Details
I'm reporting this here and not in plantuml because the exact same block works fine with `.. uml::`.

**Comment by danwos** [comment]
Thanks for the report. :+1: 

Can you activate the `debug` option please, then the generated, finally used UML code gets printed under your diagram.
This makes the debugging much easier :)

```
.. needuml::
   :debug:
```

**Comment by AlexanderLanin** [comment]
The output is

```
@startuml
allowmixing

!include <C4/C4_Container>

Container(c1, "Container 1")
Container(c2, "Container 2")

Rel(c1, c2, "uses")
@enduml
```

when I render that via plantuml it indeed doesn't work.
But now I see a proper error message :)
Which is not helpful at all... :(

![image](https://user-images.githubusercontent.com/5074553/191952199-25836393-ed07-43d9-ad97-9d5edf096003.png)


However it is fixed by removing the line which says `allowmixing`. I guess `allowmixing` is added by needuml?

**Comment by AlexanderLanin** [comment]
`c1 --> c2` is fine with allowmixing, `c1 -->> c2` is not.

**Comment by danwos** [comment]
That's right, ``allowmixing`` is set by Sphinx-Needs.
I didn't know that it can make such trouble.

Looks like we need to configure it somehow and add a Sphinx-needs config option to ``conf.py``:
```
needs_uml_allowmixing = False
```

If `True` `needuml` will add `allowmixing` automatically to **all** ``needuml`` diagrams. (current behavior)
If `False`, user have to set it.
Default is `True`.

Would this be helpful?

**Comment by AlexanderLanin** [comment]
After looking at it some more, it comes down to something really stupid... as usual.

After updating to sphinx-needs 1.0.2 the preview in VS Code will be fixed only after a restart of VS Code.
