### ISSUE TITLE
Rendering issue when debug layout is used

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-needs#721]
Similar to #691, when `debug` layout is used, the following were observed with RTD theme.

1. For needs on which debug layout is used, no expand/collapse button appears
2. For ALL needs in the page where a debug layout is used for one or more needs, both collapse/expand buttons as in the above issue appears.

I did not test if this PR automatically solved this problem. 
https://github.com/useblocks/sphinx-needs/pull/716
Else please check.

**Comment by danwos** [comment]
It's also not working with out Sphinx-Immaterial theme.
See https://sphinx-needs.readthedocs.io/en/latest/layout_styles.html#EX_DEBUG

**Comment by danwos** [comment]
PR got already merged.
