### ISSUE TITLE
Idea: Implement everything in needuml and remove needarch

### ISSUE THREAD

**Issue by PhilipPartsch** [useblocks/sphinx-needs#733]
Needuml and needach are "the same". 
It would be cool, to have everything in one directive, which could detect the scope automatically.

**Comment by danwos** [comment]
We discussed this internally and I'm not a huge friend of it.

Yes, needarch and needuml share a lot of functionality and they can be used to do the same.
But some features and ideas will only work in the context of a need.
So the same directive would work differently or even produces errors, if used inside a need or not.

I find this very confusing and it is also hard to document this, so we decided to better have two directives.

BTW: It was implemented in the past as you requested. But we really struggled to explain it correctly in presentations to the user.
And I know, the current docs are not the best to explain the difference :/

So I would like to reject this request.

**Comment by PhilipPartsch** [comment]
Thanks for the clear statement. 
If you check my PR, you will see, I added `import()` and the new `need()` to needuml, too.
The reason for: to implement an exception is so much easier. Check if we are in scope of a needuml, raise the excpetion.
From my side, we can close this here.
