### ISSUE TITLE
needuml: flow() shall return plantuml text without newline

### ISSUE THREAD

**Issue by PhilipPartsch** [useblocks/sphinx-needs#737]
I want to embedded elements in other elements.
Like this:
```
@startuml
card card {
card card2
}
@enduml
```
If I do want to generate the `card card` part, flow() has to finish without a newline.
```
@startuml
{{flow("card")}} {
{{flow("card2")}}
}
@enduml
```

This is in general a breaking change, but often human do write the need newline anyway.
Example 1:
```
.. needuml::

   {{flow("e1")}}
   {{flow("e1")}}
```
has the needed newlines in the code.

Counter example to 1:
```
.. needuml::

   {{flow("e1")}}{{flow("e1")}}
```
Would in the future generate a failed plantuml syntax. 
I believe the new behaviour is intuitive, and would not generate issues.

Example 2 from scripts:
```
.. needuml::

   {% for e in filter(...) %}
   {{flow(e.id)}}
   {% endfor %}
```
Even here the script generates the needed newlines.

Counter example to 2:
```
.. needuml::

   {% for e in filter(...) %}{{flow(e.id)}}{% endfor %}
```
Would in the future generate a failed plantuml syntax. 
I believe the new behaviour is intuitive, and would not generate issues.

Any opinions?

**Comment by danwos** [comment]
I agree that newline is not needed to be set by `flow`. And in most cases, the user does it already automatically.

We could also make it configurable, like `flow("card", nl=False)`.
But I'm not sure if this is really needed and removing the newline at the end of ``flow()`` would be good enough for all scenarios.
