### ISSUE TITLE
needextend shall not throw error

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#747]
If a given ID for ``needextend`` does not exist, an exception gets thrown and the build stops.

There shall be an option ``strict``, which raises an exception only if set to ``True``, which is the default option.
If ``strict=False``, only a log-info message shall be written.

**Comment by danwos** [comment]
PR 748 already implements a quick&dirty solution.

It also adds the ``conf.py`` option ``needs_needextend_strict``, to de/activate the behavior for all ``needextends``

**Comment by danwos** [comment]
My use case: Importing data from different source, but the data may change and only a subset is loaded.

A ``.. needextend:: MY_REQ`` would make trouble, if ``MY_REQ`` got not imported, which may be ok for the current build.

May be also important for variant handling.

**Comment by twodrops** [comment]
Thanks for the issue. I wanted to request this anyways as we have situation that we have needs imported from external tools and extended with `needextend`. In local builds, we are allowed to ignore the imported needs. So this feature to make it not strict will help. Thanks.

**Comment by twodrops** [comment]
@danwos It would be nice to have this as part of 1.0.3 :)

**Comment by twodrops** [comment]
@danwos 
I noticed another behaviour that even if there is exists only one `needextend` with a wrong filter, several warnings amounting to the total number of needs (or total number of rSTs??) are thrown. Is this known? Shall I create a  separate issue?

**Comment by twodrops** [comment]
I realized that that number of warnings have come down with 1.0.3. However for every warning it still throws the same information 3 times as part of a single warning.

> WARNING: Filter MYELEMENT not valid: Error: Filter MYELEMENT not valid: Error: name 'MYELEMENT ' is not defined

**Comment by twodrops** [comment]
A wrong ID used in `needextend` now raises an exception inplace of an error.

```
.. needextend:: WRONG_ID
    :+realizes: MYELEMENT_ATTRIB_EXT

```
![image](https://user-images.githubusercontent.com/103930/203447226-795f1c37-21c9-4a15-b50c-910441b2a3d8.png)
(Build folder was emptied)

`needextract` for example behaves different and silently ignores such errors (in that way `needextract` is like `needextend` with `:strict:` as `false`)

**Comment by danwos** [comment]
The exception from @twodrops is interesting.
It claims about not being able to connect a `NeedsInvalidFilter` and a `tuple` via `%`-operand inside `directives.need`.

So it can't combine a tuple and an exception.

For me, it looks like that `directives.need` (or something else ) has not caught the exception when an invalid filter is used.
It just goes on with its code instead of throwing itself an exception, or the thrown exception-creation fails e.g. because the error-string-generation can't handle the upper `NeedsInvalidFilter`.

Needs some further code analysis.....

**Comment by twodrops** [comment]
One of my colleagues found out that the issue was in one of our own extension which was not casting `NeedsInvalidFilter` to a string before using it. So this issue I guess can be closed.
