### ISSUE TITLE
Bug in needs_render_context documentation

### ISSUE THREAD

**Issue by AlexanderLanin** [useblocks/sphinx-needs#750]
The documentation says that needs_render_context works with functions which return a string.
(By the way it doesn't show how to do that)

But it works fine with functions returning more complex types. Is that intentional?

Here is an example:
```py
def all_relations(needs, need) -> List[Tuple[Any, str, str]]:
    if isinstance(need, str):
        need = needs[need]

    result: List[Tuple[Any, str, str]] = []
    # currently only "uses" relation is supported.
    for id in need["uses"]:
        result.append((needs[id], "uses", "-->"))
    for id in need["uses_back"]:
        result.append((needs[id], "uses", "<--"))
    return result

needs_render_context = {
    "all_relations": all_relations,
}
```

And in jinja in needarch:
```
         {% for relation in all_relations(needs, need()) %}
            {% set other_need = relation[0] %}
            {% set text = relation[1] %}
            {% set arrow = relation[2] %}
            {{ need()['id'] }} {{ arrow }} {{ other_need['id'] }} : {{ text }}
         {% endfor %}
```

**Comment by PhilipPartsch** [comment]
Hi Alexander,
it is intended and needed, so it is possible to have more complex implementations. We have to enhance the documentation here.

**Comment by danwos** [comment]
Thanks for the bug report :+1: 

You are right, the function can return anything. There are also no checks for this.
And yes, I see no technical reason why it should not be allowed.
The user is responsible to deal with this data in the right way :)
And our example shows that there are use cases for it.
