### ISSUE TITLE
Memory leak: Don't save target/content nodes

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#790]
## Impact
Sphinx-Needs has a huge memory problem in bigger projects:
![image](https://user-images.githubusercontent.com/998700/201027196-89ecec7b-ab31-4434-9c29-183b5ddf76f7.png)
Runs ``3a`` and ``3b`` are the ones without fixes.
3b has 3120 pages , 3a 1560. The rest is the same.

Also we just doubled the pages, the memory consumption increased by 5.
And the test-project has just ~3k files, but we have project with ~25k files.

Runs ``3a FIXES`` and ``3b FIXES`` are containing a quick & dirty fix, to get the Python Garbage collector working correctly (see next chapter for details)

## Analysis
The reason for this are lines like this:
https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/api/need.py#L308-L314
`target_node` and the later set `content_node` are source of the problem here.

Here we store the target_node in our global needs_dict.
The target_node gets also returned to Sphinx, which puts it into the doctree.
But after each file, Sphinx serializes the doctree of the file and frees the used memory, so that the Python Garbage Collector can destroy it and reuse the memory.

But as we still have a reference to the target_node in our global needs_dict and the target node has references to parents and children, there are references left to the doctree and the Garbage Collector does not collect it.
So in the end, all doctrees stay in memory, if we keep a reference.

We use this mechanism a lot, nearly in all directives, so a lot of stuff to change.

And the changes will be complex, as we now can't just reuse the target-node as a known location in the doctree, instead we have to walk through the whole, current doctree to identify our needed node somehow else. This means changes in the architecture.

## Findings
tbd, list of locations in the code that need to be fixed

#### Source of evil
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/api/need.py#L308-L314
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/api/need.py#L482
#### target_node affects
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/need.py#L230
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/diagrams_common.py#L193
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needfilter.py#L178
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needfilter.py#L204
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needlist.py#L126

#### content_node affects
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/layout.py#L46

### needbar
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needbar.py#L135

### needextend
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needextend.py#L65

### needextract
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needextract.py#L60-L61
Also ``env`` gets stored!

### needfilter
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needfilter.py#L65-L72
Also ``env`` gets stored!

### needflow
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needflow.py#L91-L103
Also ``env`` gets stored!

* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needflow.py#L287

### needgantt
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needgantt.py#L97-L98

### needlist
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needlist.py#L53-L58
Also ``env`` gets stored!

* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/filter_common.py#L184-L185

* [x] ENV usage https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/filter_common.py#L180

### needpie
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needpie.py#L93-L94
Also ``env`` gets stored!

### needsequence
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needsequence.py#L64-L65
Also ``env`` gets stored!

* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needsequence.py#L109

### needtable
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needtable.py#L93
None???

### needuml
* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needuml.py#L91

* [x] https://github.com/useblocks/sphinx-needs/blob/bc9641f44c184325d546ddd0396336726622f20f/sphinx_needs/directives/needuml.py#L373-L377

### Technical concept
tbd. Not clear yet, how many locations we have to fix.
And I'm pretty sure the fixes will all be different and some will have an impact on the architecture.

**Comment by santiagopagani** [comment]
One thing to highlight in regards to performance is that Sphinx-Needs version 0.7.9 was considerably more performant than Sphinx-Needs 1.0.2.
For example, we have a project that has around 5k needs. When compiling it with Sphinx-Needs version 0.7.9 we have observed build times of 12 minutes in average. However, the same project compiled on the same machine with Sphinx-Needs version 1.0.2 takes over 2.5 hours.
