### ISSUE TITLE
Expand/Collapse button does not work

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-needs#795]

**Comment by PhilipPartsch** [comment]
Looks like it come in with this:
https://github.com/useblocks/sphinx-needs/commit/970cdaade756a957c725297b8e4471cd629d9ae2
Shall we change back the js and css changes?

**Comment by twodrops** [comment]
Could we make sure that there is a test for this so that it does not fail in the future again?

**Comment by danwos** [comment]
No, we should not revert it, as it was a fix for a problem. But it looks like something else has also changed.

We are also taking already a look into JEST to test our JavaScript in sphinx-needs in future.

**Comment by danwos** [comment]
Solved via #810.

**Comment by danwos** [comment]
We are facing still some issues, if not tested locally.
