### ISSUE TITLE
NotImplementedError: <class 'sphinx.writers.latex.LaTeXTranslator'> departing unknown node type: NeedRef

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [useblocks/sphinx-needs#796]
Exception occurred:
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 2040, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.latex.LaTeXTranslator'> departing unknown node type: NeedRef
The full traceback has been saved in /var/folders/vf/rxgmxgc5225gcwgk4g9c8yq40000gn/T/sphinx-err-o5uk2ndy.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [latexpdf] Error 1

apears with

Sphinx 5.2.3, 5.3, 6.0b
docutils 0.19

on command make singlehtml or make latexpdf

# Python version: 3.10.8 (CPython)
# Docutils version: 0.19 
# Jinja2 version: 3.1.2
# Last messages:
#   _legal/Information
#   _finalchapter/figs
#   _finalchapter/tables
#   _finalchapter/bib
#   _finalchapter/final
#   
#   resolving references...
#   erledigt
#   writing...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/local/lib/python3.10/site-packages/alabaster/__init__.py
#   sphinxcontrib.blockdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/blockdiag.py
#   sphinxcontrib.actdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/actdiag.py
#   sphinxcontrib.nwdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/nwdiag.py
#   sphinxcontrib.rackdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/rackdiag.py
#   sphinxcontrib.packetdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/packetdiag.py
#   sphinxcontrib.seqdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/seqdiag.py
#   sphinx.ext.autodoc.preserve_defaults (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc.typehints (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/typehints.py
#   sphinx.ext.autodoc (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.coverage (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.doctest (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.extlinks (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.githubpages (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/githubpages.py
#   sphinx.ext.graphviz (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.ifconfig (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.imgconverter (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/imgconverter.py
#   sphinx.ext.imgmath (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/imgmath.py
#   sphinx.ext.inheritance_diagram (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/inheritance_diagram.py
#   sphinx.ext.intersphinx (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.napoleon (6.0.0b2) from /usr/local/lib/python3.10/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx_sitemap (unknown version) from /usr/local/lib/python3.10/site-packages/sphinx_sitemap/__init__.py
#   sphinxcontrib.plantuml (unknown version) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/plantuml.py
#   sphinxcontrib.autoyaml (unknown version) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/autoyaml/__init__.py
#   sphinxcontrib.details.directive (0.1.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/details/directive/__init__.py
#   sphinx_data_viewer (0.1.2) from /usr/local/lib/python3.10/site-packages/sphinx_data_viewer/__init__.py
#   sphinx_needs (1.0.3) from /usr/local/lib/python3.10/site-packages/sphinx_needs/__init__.py
#   sphinxawesome_theme.jinja_functions (3.3.7) from /usr/local/lib/python3.10/site-packages/sphinxawesome_theme/jinja_functions.py
#   sphinxawesome_theme (3.3.7) from /usr/local/lib/python3.10/site-packages/sphinxawesome_theme/__init__.py
#   sphinxcontrib.bibtex (2.5.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/bibtex/__init__.py
#   myst_parser (0.18.1) from /usr/local/lib/python3.10/site-packages/myst_parser/__init__.py
#   sphinxawesome_theme.highlighting (3.3.7) from /usr/local/lib/python3.10/site-packages/sphinxawesome_theme/highlighting.py
#   sphinxawesome_theme.html_translator (3.3.7) from /usr/local/lib/python3.10/site-packages/sphinxawesome_theme/html_translator.py
#   sphinxawesome_theme.postprocess (3.3.7) from /usr/local/lib/python3.10/site-packages/sphinxawesome_theme/postprocess.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/local/lib/python3.10/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 307, in build_update
    self.build(['__all__'], to_build)
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 376, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/latex/__init__.py", line 304, in write
    docwriter.write(doctree, destination)
  File "/usr/local/lib/python3.10/site-packages/docutils/writers/__init__.py", line 77, in write
    self.translate()
  File "/usr/local/lib/python3.10/site-packages/sphinx/writers/latex.py", line 86, in translate
    self.document.walkabout(visitor)
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 199, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/local/lib/python3.10/site-packages/sphinx/util/docutils.py", line 585, in dispatch_departure
    super().dispatch_departure(node)
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 2018, in dispatch_departure
    return method(node)
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 2040, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.latex.LaTeXTranslator'> departing unknown node type: NeedRef

**Comment by danwos** [comment]
Thanks for the report.
Can you tell me which Sphinx-Needs version have you used, or is it directly from master?

**Comment by Pierre-Gronau-ndaal** [comment]
Hi,pypi version offered 1.03Many thanks in advance for your support.-- 

Kindly regards/herzliche Grüße
Pierre Gronaundaal Gesellschaft für Sicherheit in der Informationstechnik mbH & Co KGGeschäftsführer Carsten DingendahlHQ:Mathias-Brüggen-Str. 16050829 KölnOffice:Christophstr. 15-1750670 KölnDEUTSCHLANDTelefon: +49 151 419 867 35Fax: +49 32 121 023 ***@***.*** K       HRA 35474Komplementärin   XSTeam Beteiligungs GmbHGeschäftsführer   Carsten DingendahlAmtsgericht K       HRB 105499Am 17.11.2022 um 14:33 schrieb Daniel Woste ***@***.***>:﻿
Thanks for the report.
Can you tell me which Sphinx-Needs version have you used, or is it directly from master?

**Comment by danwos** [comment]
Sorry to say, but I'm unable to reproduce your problem.
I was able to build some of our test projects with ``singlehtml`` or ``latex``.

Your error message looks like a bug on master, which I'm currently working on.
But this bug was not released  with 1.0.3, so you should not have it if installed from PyPI and not from master branch.

Can you maybe provide an example project, which reproduces the error?

Off-topic: It looks like you are trying to build PDFs. Have you tried https://sphinx-simplepdf.readthedocs.io? ;)

**Comment by Pierre-Gronau-ndaal** [comment]
Hi,I‘m sorry to write ✍️ It is installed by pip3 - no master involved.If I disable Sphinx needs - it works … If you like I will give you my conf.py the content if confidential and 3GB …-- 

Kindly regards/herzliche Grüße
Pierre Gronaundaal Gesellschaft für Sicherheit in der Informationstechnik mbH & Co KGGeschäftsführer Carsten DingendahlHQ:Mathias-Brüggen-Str. 16050829 KölnOffice:Christophstr. 15-1750670 KölnDEUTSCHLANDTelefon: +49 151 419 867 35Fax: +49 32 121 023 ***@***.*** K       HRA 35474Komplementärin   XSTeam Beteiligungs GmbHGeschäftsführer   Carsten DingendahlAmtsgericht K       HRB 105499Am 17.11.2022 um 16:05 schrieb Daniel Woste ***@***.***>:﻿
Sorry to say, but I'm unable to reproduce your problem.
I was able to build some of our test projects with singlehtml or latex.
Your error message looks like a bug on master, which I'm currently working on.
But this bug was not released  with 1.0.3, so you should not have it if installed from PyPI and not from master branch.
Can you maybe provide an example project, which reproduces the error?
Off-topic: It looks like you are trying to build PDFs. Have you tried https://sphinx-simplepdf.readthedocs.io? ;)

**Comment by danwos** [comment]
Can you do me a pleasure and install the latest version from master: `pip install https://github.com/useblocks/sphinx-needs.git`.

Also, do you use the parallel build option from Sphinx? something like `sphinx-build -j auto` or so.

**Comment by Gabsha** [comment]
Hello!
I can confirm that I'm facing the same issue. With version `1.0.2` it works fine, but with `1.0.3` and `master` I'm seeing the same exception raised. I am not using any other options from sphinx-build : `sphinx-build -M latexpdf "doc" "_out/doc"`. The `html` builder works fine, but not the `singlehtml` nor the `latexpdf` ones.

```
Exception occurred:
  File "/home/<me>/docs/_venv/lib/python3.10/site-packages/docutils/nodes.py", line 2068, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.latex.LaTeXTranslator'> departing unknown node type: Needtable
The full traceback has been saved in /tmp/sphinx-err-e_d_td3i.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Here is the full traceback (only difference for `singlehtml` is the `sphinx-writers.html5.HTML5Translator` raising the exc.)

```
# Sphinx version: 5.0.2
# Python version: 3.10.8 (CPython)
# Docutils version: 0.18.1 release
# Jinja2 version: 3.1.2
# Last messages:
#   background
#   views
#   traces
#   references
#   api
#   
#   resolving references...
#   done
#   writing...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (5.0.2) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/perso/docs/_venv/lib/python3.10/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (5.0.2) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (5.0.2) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.todo (5.0.2) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (5.0.2) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.viewcode (5.0.2) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.napoleon (5.0.2) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx_autodoc_typehints (unknown version) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx_autodoc_typehints/__init__.py
#   sphinx_data_viewer (0.1.2) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx_data_viewer/__init__.py
#   sphinx_needs (1.0.3) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinx_needs/__init__.py
#   sphinxcontrib.plantuml (unknown version) from /home/perso/docs/_venv/lib/python3.10/site-packages/sphinxcontrib/plantuml.py
Traceback (most recent call last):
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 285, in build_update
    self.build(['__all__'], to_build)
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 352, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/builders/latex/__init__.py", line 301, in write
    docwriter.write(doctree, destination)
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/writers/latex.py", line 86, in translate
    self.document.walkabout(visitor)
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/docutils/nodes.py", line 199, in walkabout
    if child.walkabout(visitor):
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/docutils/nodes.py", line 199, in walkabout
    if child.walkabout(visitor):
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/docutils/nodes.py", line 199, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 5 more times]
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/docutils/nodes.py", line 212, in walkabout
    visitor.dispatch_departure(self)
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/sphinx/util/docutils.py", line 546, in dispatch_departure
    super().dispatch_departure(node)
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/docutils/nodes.py", line 2046, in dispatch_departure
    return method(node)
  File "/home/perso/docs/_venv/lib/python3.10/site-packages/docutils/nodes.py", line 2068, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.latex.LaTeXTranslator'> departing unknown node type: Needtable
```

**Comment by tim-nordell-nimbelink** [comment]
I also encountered this in 1.0.3; I was able to make a patch that fixed the issue locally by assigning a dummy visitor to each node.  I don't know if this is the correct way to fix it or not.

**Comment by danwos** [comment]
Thanks for the PR, but I don't think that this really solves the problem.

Normally there should not be any docutils nodes of type "sphinx-needs" (needref, needtable, ...) left in the doctree, as all of them get converted to standard docutils nodes. 
If the stay in the doctree and the above error gets thrown, this normally means that their overall handler-routine has not been called and that the data will also be wrong.

As we have no data/function based test cases for latex/pdf builds, we can only figure this out by hand.

I might be wrong, as I'm not an export for the late build. But do you see the references of one need to another need in your latex/pdf code?

**Comment by tim-nordell-nimbelink** [comment]
@danwos Some of the references are correct, and some are not.  Looking closer, I can see that the needs-list for instance didn't render, so this doesn't fix that.  (I guess it just masks the underlying issue.)

FYI, commit 311b9dce76404dbc23f085787adafaca8fe2ab97 is what broke things here for the LaTeX output  (I did a `git bisect`).

**Comment by danwos** [comment]
Thanks for diving deeper and figuring out the commit. :+1:
Have you tested the current version from master?
There was a fix for some problems introduced with the mentioned commit.

**Comment by tim-nordell-nimbelink** [comment]
I just tested `master`, and it's broken there.  Let me see if I can create a minimal docker environment to reproduce.

**Comment by danwos** [comment]
With commit 311b9dce76404dbc23f085787adafaca8fe2ab a new system was introduced to find all Sphinx-Needs nodes in the doctree and call the related handler. 

We had a similar bug with a HTML build, reason was that not all files got checked for Sphinx-Needs nodes.
But I have absolutely no idea why this mechanism should behave different related to the builder, as it is done before the builder gets executed.

**Comment by danwos** [comment]
I'm able to reproduce it with the Sphinx-Needs docs and command `sphinx-build -M latexpdf . _build -v`

**Comment by danwos** [comment]
Created PR #806, which currently contains a test case only.

I already figured out the reason for the problem.
the `process_caller` from [here](https://github.com/useblocks/sphinx-needs/blob/master/sphinx_needs/needs.py#L414) is responsible for calling the related node-handlers (which replace in the end the need-nodes).

This ``process_caller`` must be called for each doctree, so for each rst-file, as there is one doctree per file.
This works for ``html`` builder, which calls the `process_caller` 3 times: index, page_1, pages_2 (related to the test case in PR #806).

For `latex` builder, it gets only called once, just for the index page.
The same for the `singlehtml` builder.

That's the reason why the nodes from the other files (here page_1, page_2) do not get replaced.

I guess the builder is somehow merging the different doctrees into one doctree, to get a single one for a single output file.
But our node-handlers gets not called for the other files, as the related event  "doctree-resolved" gets not fired for the other files by the  `latex` and `singlehtml` builders.

I have to check their code to understand the reason for this behavior.

**Comment by tim-nordell-nimbelink** [comment]
Interesting.

From https://www.sphinx-doc.org/en/master/extdev/appapi.html they indicate that the pages are joined into a single doc tree:

```
# The updated-docs list can be builder dependent, but generally includes all new/changed documents,
# plus any output from `env-get-updated`, and then all "parent" documents in the ToC tree
# For builders that output a single page, they are first joined into a single doctree before post-transforms
# or the doctree-resolved event is emitted
for docname in updated-docs:
   13. apply post-transforms (by priority): docutils.document -> docutils.document
   14. event.doctree-resolved(app, doctree, docname)
       - In the event that any reference nodes fail to resolve, the following may emit:
       - event.missing-reference(env, node, contnode)
       - event.warn-missing-reference(domain, node)
```

I wonder if the join code currently requires the nodes to be resolvable (for whatever reason) before invoking the `doctree-resolved` event?

**Comment by danwos** [comment]
Found (hopefully) a solution for it, which is also quite simple.

As the file `index` contains the "master"-doctree for single-output-file builders like `latext` or `singlehtml`, Sphinx-Needs will always check the doctree for `index` and ignores it's internal list of files, which contain sphinx-needs elements.

At least my test case works one.
@tim-nordell-nimbelink can you maybe check PR 806, if it works for your document projects?
Maybe you have some corner cases, which my simple test case does not cover yet.

**Comment by tim-nordell-nimbelink** [comment]
@danwos I just tried it here, and it appears to work.  Thanks!

**Comment by tim-nordell-nimbelink** [comment]
@danwos I do get errors in the LaTeX output that says labels are "multiply defined":

```
Latex found 146 multiply defined reference(s)
```

That's new in this commit vs 1.0.2 - might be related?

**Comment by danwos** [comment]
Mmh it should not, the internal way of creating the output data was not really touched.

Can you see what the name of the reference is? And does the number 146 tell you something? Maybe the number of needs in your docs multiplied by 2, or something like this...

**Comment by danwos** [comment]
Feel free to reopen, if the fix is not working in some cases.
Or even create a new issue, if we now have additional problems, which I really don't hope.

Thanks all for your help and ideas :+1:
