### ISSUE TITLE
Sphinx-Needs 1.0.3 has a dependency to a matplotlib version but it is not marked as such in Sphinx-Needs pip package

### ISSUE THREAD

**Issue by santiagopagani** [useblocks/sphinx-needs#800]
While upgrading a server from Sphinx-Needs 0.7.9 to Sphinx-Needs 1.0.3, we noticed that the build was failing for some `needpie` directive. After looking into the issue, it turns out we had installed `matplotlib==3.1.2`, but Sphinx-Needs 1.0.3 (and potentially also 1.0.2 or 1.0.1 but I did not test it) require a higher version of `matplotlib`, but this was not marked in the dependencies of the pip package.

With matplotlib 3.4.2 (potentially also a lower version, but have not tested it) it works fine.
It would be nice to mark such a dependency to the matplotlib version in Sphinx-Needs pip package.

**Comment by iSOLveIT** [comment]
@danwos

**Comment by danwos** [comment]
Thanks for reporting :+1: 
The lowest supported version is `3.3.0`.
Fix got already merged.
