### ISSUE TITLE
Needpie: extra options are not recognized

### ISSUE THREAD

**Issue by shreyascs91** [useblocks/sphinx-needs#826]
Unable to use data from extra options in a needpie definition.
Example:
.. needpie:: Customer Requirement overview
   :labels: new, no_req, in_analysis
   
   type == 'cust_req' and 'RB_FBL_Status' == 'new'
   type == 'cust_req' and 'RB_FBL_Status' == 'no_req'
   type == 'cust_req' and 'RB_FBL_Status' == 'in_analysis'

in the above example, the extra option 'RB_FBL_status' is marked invalid during build.

**Comment by danwos** [comment]
I'm not sure if your filter strings are correct.
For me it should be `type == 'cust_req' and RB_FBL_Status == 'new'` as `RB_FBL_Status` is not a string.

I also updated our `needpie` test case and created a needpie based on an `extra_option`.
Take a look at the files of  [PR #827](https://github.com/useblocks/sphinx-needs/pull/827/files).

So from my side, this should work.

But maybe, as your option names contains lower/upper characters and also `_`, we have a problem here with the correct option-name. Can you check it with a simpler extra_option, like `fbl_status`?

**Comment by shreyascs91** [comment]
changing to lowercase (RB_FBL_Status --> rb_fbl_status) worked.
Thank you.

**Comment by shreyascs91** [comment]
changing to lowercase (RB_FBL_Status --> rb_fbl_status) worked.
