### ISSUE TITLE
Could not import extension sphinx_needs (exception: No module named 'pygls.lsp.methods')

### ISSUE THREAD

**Issue by rsarrazin2** [useblocks/sphinx-needs#828]
sphinx-needs version: 1.1.0
environment: Ubuntu 20.04

After installing sphinx-needs with `pip install sphinx-needs` I get the broken requirement error `esbonio 0.15.0 has requirement pygls<1.0,>=0.11.0; python_version < "3.11", but you have pygls 1.0.0.` then, when running sphinx with needs, `Could not import extension sphinx_needs (exception: No module named 'pygls.lsp.methods')`.

This may relate to the newest pygls release (1.0.0 released 4 days ago, see https://pypi.org/project/pygls/#history).

When I force the pygls version to the previous version 0.13.1, I don't get any broken requirement anymore, and sphinx with needs runs as expected.

**Comment by rsarrazin2** [comment]
Note this quote in https://github.com/openlawlibrary/pygls/blob/master/docs/source/pages/migrating-to-v1.rst:
> The most notable change of the v1.0 release of pygls is the removal of its hand written LSP type and method definitions.

This matches the error message `No module named 'pygls.lsp.methods'`.

**Comment by cedossan** [comment]
Indeed, it seems related to https://github.com/useblocks/sphinx-needs/blob/master/pyproject.toml#L45. Need to be changed to a fixed version (0.13.1) on a new PR

**Comment by danwos** [comment]
We created a new release today (1.2.1), which supports older and newer esbonio/pygls versions.
So I close this one, as it should be fixed. If not, feel free to reopen.

Duplicates also #865, #867
