### ISSUE TITLE
Update jsonschema dependency

### ISSUE THREAD

**Issue by aacebedo** [useblocks/sphinx-needs#847]
Is it possible to update the jsonschema dependency ?
It is still on 3.2.0 and it prevents me to package `sphinx-needs` for NixOS.

3.2.0 is from 2019, current version is 4.17.3.

**Comment by danwos** [comment]
Thanks for asking, and yes this should be possible.
I see no reason to pin it this hard to 3.2.0.

**Comment by aacebedo** [comment]
great ! I made the patch temporarily in the nix package and it seems to work. I simply change =3.2.0 to >=3.2.0

**Comment by danwos** [comment]
Done with PR #848
