### ISSUE TITLE
Build error when using the add_need API

### ISSUE THREAD

**Issue by adegroote** [useblocks/sphinx-needs#851]
When switching to sphinx_needs 1.1.1, our build now fails with:

```
KeyError: 'extra_options'
```

It comes from  

```    
needs_extra_option_names = NEEDS_CONFIG.get("extra_options").keys()
``` 

(need.py:280)

The issue appears when we call add_need in own of our directive,  in a scenario relatively similar to the one documented. Is there an issue on our side ? Do we need to do something to ensure NEEDS_CONFIG is properly constructed before calling add_need ? 

Thanks in advance

**Comment by danwos** [comment]
Mhh that's strange, as Sphinx-Needs itself is using this option for each need internally.

I know this behavior from development, when the Sphinx cache is used by accident.
Are you sure you have tested it with a clean build?

**Comment by adegroote** [comment]
I can confirm that I'm able to reproduce it with a clean build in my main project. Through, I'm not yet able to find s a smaller reproducer.

**Comment by danwos** [comment]
I think the API has slightly changed and a new parameter 'jinja_content' was added at the end, before the kwarg extra_options is set.
Maybe this is the reason and your script just need to take this option into account when using 'add_need'.

**Comment by adegroote** [comment]
In the end, the issue was the plugin use the old API (sphinxcontrib.needs) vs the new one used in the project. Sorry for the noise.
