### ISSUE TITLE
Needs inside included file generates a sphinx error for identical ID

### ISSUE THREAD

**Issue by Thylowz** [useblocks/sphinx-needs#864]
I was trying to make sphinx-needs work for my document project, but there is an issue that is blocking:

All my requirements are stored in a dedicated folder withing <req_id>.rst files, and included in a parent .rst file (via `.. include::` directive)

I don't know exactly how it happens, but when building, the requirement ID is wrongly seen twice, whereas if I put it directly in my parent **rst** file, it's OK.

**Comment by danwos** [comment]
Sphinx renders all rst files, which it can find.

Do inn your case the same need object is defined twice, once in the original rst and once in the file with the include statement.

You should configure the Sphinx exclude_pattern to ignore your original rst files

**Comment by Thylowz** [comment]
Ok thanks for the explanation. It indeed works to set my requirements directory in the exclude_pattern.

I know it's not the proper way to ask, but I have an additional question: I saw that images exist both as png and svg. Is there a way to specify you want to use a format over the other (since I want to generate docx files and SVG is not really supported by docxbuilder).

**Comment by danwos** [comment]
For plantuml-related images (needflow, needsequence) you can use the sphinxcontrib-plantuml options in your conf.py to define the generated layout.
See `plantuml_output_format` at https://github.com/sphinx-contrib/plantuml/#configuration

For matplotlib-based images (needpie, needbar) multiple formats get rendered and the later builder decides automatically which format to use. The image generation does not cost so much performance, as the earlier value calculation and chart-defintion happens only once. Based on this the final image export happens.

Does something not work with the docxbuilder, or is it the case that not needed image formats are available on the disk?

**Comment by danwos** [comment]
I close this issue, as the original problem got solved.
