### ISSUE TITLE
The pygls.lsp.types module no longer exists

### ISSUE THREAD

**Issue by ivanayov** [useblocks/sphinx-needs#865]
In the latest [pygls release](https://pygls.readthedocs.io/_/downloads/en/latest/pdf/), the `pygls.lsp.types` module no longer exists, which results to a build failure:
```
ModuleNotFoundError: No module named 'pygls.lsp.types'
```

I'm using sphinx-needs v1.2.0.

**Comment by arwedus** [comment]
@ivanayov: Thanks for reporting this issue, I have noticed this, too. Background: sphinx-needs is not yet compatible with pygls 1.0, but does not pin the version dependency to pygls<1.0.

@danwos: This is an issue if people upgrade esbonio to 0.16.0, which depends on pygls 1.0.

I see two options:

a) mini release which pins the version dependency of pygls
b) migrating the pygls.lsp usage in esbonio.py

**Comment by danwos** [comment]
Thanks for the reporting.
A quick fix on your side would be to install esbonio < 0.16.

However, we are working on a fix, which allows supporting older and newer esbonio versions: #868.

We don't want to pin the version or support only newer versions in our code, as I see scenarios, where older versions may still be needed in the currently used Python env.
For instance: The Restructured-VsCode-Extension may force us to use the older esbonio version.

I hope we can merge the PR today and create a new release.

**Comment by danwos** [comment]
This got fixed by #868.
I will create a new release shortly.

Thanks all for the help :+1:
