### ISSUE TITLE
sphinx-needs minor version update 1.2 introduces a breaking change

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinx-needs#871]
@danwos : The minor version update `1.2.0` introduces a dependency on `jsonschema>3.2`, which in effect results in jsonschema 4.x

jsonschema major version update is a breaking change that results in one of our integration test frameworks in our (big) project to generate errors.

If you want to apply semantic versioning, the rule would be:
Every major version change in one of your requirements results in a major version change in your package.

i.e. the major version change of jsonschema to support only 4.x would have required a major version change in sphinx-needs to 2.x.

If you do not feel like jumping to a newer major version - would it be possible to support both jsonschema 3.x and 4.x?

**Comment by danwos** [comment]
I think we just have been too strict with the needed jsonschema version.
It was `3.2.0`, then moved to `>3.2.0`, which excludes `3.2.0` itself, which we still support.

So PR #872 sets it to `>=3.2.0` and that's it :)

**Comment by danwos** [comment]
Fixed by merged #872
