### ISSUE TITLE
collapse not working in options and in html

### ISSUE THREAD

**Issue by kreuzberger** [useblocks/sphinx-needs#882]
Using sphinx-needs 1.2.2 i cannot

- configure the needs with `:collapse: TRUE` any more
- button in html output is without any effect.

This occurs for me using
- different html themes ("nature", "alabaster")
- different browser (firefox, brave).

Due to the history this should be fixed, but still occurs for me using the extension. 
It seems NOT to occur in the tests of sphinx-needs.

How could this helped to debug? The script file itself "sphinx_needs_collapse.js" gets loaded but the function seems not to be called

**Comment by kreuzberger** [comment]
Due to the official documentation i miss the jquery library and this seems to be true. jquery.js is missing in _static folder also like the <script> directives in the generated html.
Any ideas why they are not added?

**Comment by danwos** [comment]
Thanks for reporting.

On our documentation, it is working:
https://sphinx-needs.readthedocs.io/en/latest/directives/need.html#collapse

But there we are not using the mentioned themes.

But I have some other internal projects (some using Alabaster) and there it also looks good.

Some weeks ago we have introduced frontend-tests with cypress.
Test cases are here: https://github.com/useblocks/sphinx-needs/tree/master/tests/js_test
The results for the last execution also looks good: https://github.com/useblocks/sphinx-needs/actions/runs/4204697660
But for sure, they are not testing every theme

**Comment by danwos** [comment]
> Due to the official documentation i miss the jquery library and this seems to be true. jquery.js is missing in _static folder also like the <script> directives in the generated html. Any ideas why they are not added?

Ahh yes, I think your Sphinx version is `>=6.0`, then Sphinx does not provide jQuery anymore.
You can use this one as a quick solution: https://github.com/sphinx-contrib/jquery

We need to add this also as dependency for the upcoming release.

**Comment by kreuzberger** [comment]
Using this exentsion the jquery is added to the generated html.
The error message is still the same.
```
Uncaught ReferenceError: $ is not defined
    <anonymous> 
sphinx_needs_collapse.js:4:1
```


```
   <script integrity="sha384-vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfGK" src="_static/jquery.js"></script>
    <script integrity="sha384-lSZeSIVKp9myfKbDQ3GkN/KHjUc+mzg17VKDN4Y2kUeBSJioB9QSM639vM9fuY//" src="_static/_sphinx_javascript_frameworks_compat.js"></script>
    <script data-url_root="./" id="documentation_options" src="_static/documentation_options.js"></script>
    <script src="_static/doctools.js"></script>
    <script src="_static/sphinx_highlight.js"></script>
    <script src="_static/translations.js"></script>
    <script src="_static/assets/jsonview.bundle.js"></script>
    <script src="_static/assets/jsonview_loader.js"></script>
    <script src="_static/sphinx-needs/libs/html/datatables.min.js"></script>
    <script src="_static/sphinx-needs/libs/html/datatables_loader.js"></script>
    <script src="_static/sphinx-needs/libs/html/sphinx_needs_collapse.js"></script>
```

**Comment by kreuzberger** [comment]
Removing the integrity attribute fixed the issue.

**Comment by kreuzberger** [comment]
Using a local copy of the extension without integrity check
