### ISSUE TITLE
Fails to show needtable in Safari

### ISSUE THREAD

**Issue by ivanayov** [useblocks/sphinx-needs#884]
Hi,

I'm generating a `need table` and it's visualised successfully in Chrome:

<img width="1151" alt="Screenshot 2023-02-24 at 22 25 43" src="https://user-images.githubusercontent.com/4160133/221285050-6053667f-1a32-4b0e-9ca6-21bb91b2b9b3.png">

But it doesn't load on Safari. The only error I can see is:

<img width="1556" alt="Screenshot 2023-02-24 at 22 27 23" src="https://user-images.githubusercontent.com/4160133/221285045-1efb35a5-c4cc-4561-8cdc-17dab0fc079a.png">

**Comment by danwos** [comment]
Sorry for the late response.
For me the table looks in both browser, as it normally takes the complete width of the right side (same as text).

There are known issues with the ReadTheDocs theme, which injects and changes some HTML table elements via javascript. Therefor our CSS style get not taken into account.

Can you check it with another theme, maybe the standard alabaster theme?
Then we know if there are Safari specific issues.

**Comment by ivanayov** [comment]
Hi,

Thank you for the reply. I tried the alabaster and the classic theme and both don't populate the table, which was working well with the sphinx theme.

**Comment by ivanayov** [comment]
Resolved
