### ISSUE TITLE
Esbonio Hover feature is broken because positon in not an iterable object

### ISSUE THREAD

**Issue by aniketsalve22** [useblocks/sphinx-needs#893]
https://github.com/useblocks/sphinx-needs/blob/6d7740f0c13aa4c089a4a2747c1ae91cd305131a/sphinx_needs/lsp/esbonio.py#L245

When I hover over a directive in rst file it throws following error

![image](https://user-images.githubusercontent.com/14127049/225291335-5b2cbe5c-487b-443c-b958-c1ae75c46b2e.png)

Versions:
sphinx-needs=1.2.2
esbonio=0.16.1

Old implementation of pygls had Position class with iterable functionality, but the new Postion class from lsprotocol is not iterable.
So the  position class must be unpacked manually

Reference:
Old pygls Position class: https://github.com/openlawlibrary/pygls/blob/fb80b8c40bc1e92a15f03ab79316abd5712fbd4b/pygls/lsp/types/basic_structures.py#L114 

New lsprotocol Position class:
https://github.com/microsoft/lsprotocol/blob/5190589485854de246bf0045a9bc52533899592e/packages/python/lsprotocol/types.py#L5480

**Comment by chrisjsewell** [comment]
this module is no longer part of sphinx-needs
