### ISSUE TITLE
Add option to profile dynamic_functions

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinx-needs#917]
Hi @danwos, we are experiencing slow build times in our project. A first profiling analysis with `py-spy` showed that a lot of time is spent in the write phase, and most of that time is spent in sphinx-needs. We suspect dynamic functions to be an issue, but we can't easily test because there is no "global dynamic function ignore" Option. So the first thing I want to do is to add a sphinx-internal profiler option for summarizing CPU time spent in dynamic functions:

https://sphinx-needs.readthedocs.io/en/latest/performance/index.html#profiling

- add NEEDS_DYNAMIC_FUNCTIONS as an option to NEEDS_PROFILING please :)

**Comment by danwos** [comment]
Using the profiler here will not be so easy, as there a multiple dynamic functions which need to get their own profiling.
Also the current implementation stores the profile of the last call only, so you don't get any information like:

* How often was the function executed?
* What are min, max and avg execution time?
* What are the given arguments for the `max` time?

I think the above information are for the beginning more important, to get an overview about what gets executed and where is the bottleneck. After that using `profiling* would be the next step.

So here is my technical concept proposal :)

## technical concept

* Provide a function and wrapper `measure`, which measures the execution amount and time of selected functions.
* `measure()` shall take the following parameters
    * `name`: Used name in documentation
    * `*args`: send to original function
    * `**kwargs`: send to original function

* Store the final results in a `json` file.
* Provide a new config option `needs_debug_measurement`. If `True` **all** implemented measurements will be activated. So no specific selection of an area, like for `profiling`.
* Implement `measurements` for the following features/functions:

  * dynamic functions. One measurement per function!
  * filter functions. One measurement per function!
  * needtable
  * needflow
  * Bigger blocks like Read & Write phase or events (not sure if easily doable)

* Add a new directive `needmeasurments`, which takes the json result and adds a small report to the sphinx documentation. Maybe the measurement keyword can be given.

**Comment by danwos** [comment]
I created a first prototype, which can measure the execution time of internal functions.
But no support for dynamic functions, yet. But this should be done fast.
Draft PR #919

It allows to the decoration of certain functions in the code via ``@measure_time()``.
And if `needs_debug_measurement` is set in `conf.py` to `True`, **all** of these functions will get measured and the following reporting is done:

* Small print out on console
* JSON file with all data, incl. function name, path, line number and docs. In build folder
* Ugly HTML report.. In build folder

**Steps to do**:
- Activate it for dynamic and filter functions
- Write documentaation
- Write test cases
- Figure out how big the overhead is if activated.
- Test it with bigger docs


### Console output
![image](https://user-images.githubusercontent.com/998700/234846185-fdc491ca-6ccb-4029-8fa9-efcf3d2f05a3.png)

### HTML output
![image](https://user-images.githubusercontent.com/998700/234846307-2477543d-915e-486f-98c2-827f90415346.png)

### JSON Structure
![image](https://user-images.githubusercontent.com/998700/234846388-503f1880-69f6-44e9-97cb-febfd9ab8642.png)

**Comment by danwos** [comment]
Small update in the PR:
* Dynamic functions and filter functions get measured
* Measurements are now categorized and the source (internal, user) is stored
* Better HTML report with more data

From the function point of view, I'm happy with the current status.
Will finalize docs and tests and that's it :)

![image](https://user-images.githubusercontent.com/998700/234993804-4b795301-515f-4506-bdf5-5387f4acf87f.png)
