### ISSUE TITLE
Feature: Suppress info messages if allow_dead_links is set to True

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinx-needs#920]
Hi @danwos,

I wanted to use a custom extension that adds SW packages and their dependencies, without warnings if the dependency link target cannot be found (because it is not necessary). I.e., I configured the option:

```py
needs_extra_links = [
    dict(option="depends", outgoing="depends on package", incoming="is depended by", allow_dead_links=True),
    # ...
]
```

I still see this info message a lot, and my request is to add some option to completely get rid of it:

```
Needs: outgoing linked need package_1 not found (document: package2/index, source need package2 on line 148 )
```

Maybe global suppression of needs info messages, or by configuring which info messages to suppress, or by changing the behavior of the `allow_dead_links` feature.

What do you think?

**Comment by danwos** [comment]
Sphinx-Needs uses the Sphinx logger to inform the user.
So Sphinx itself decides how and when stuff gets printed.

I see possible solutions here:
1. Deactivate info-message for **all** dead_link findings, if ``allow_dead_links == True``.
2. Think about a new Sphinx extension to suppress certain info messages directly in Sphinx.

1) Ist easily to do and in the scope of this project. 
So let's implement it. 

2) Would be also great, as I have seen such requests for filtering log messages a lot.
Hopefully find some time to work on a prototype.

## Technical concept

New config variable ``report_dead_links``.
 If ``True`` a normal output will be written. If ``False`` no output/warnings/infos or whatever.
