### ISSUE TITLE
filter strings multiline

### ISSUE THREAD

**Issue by kreuzberger** [useblocks/sphinx-needs#946]
When giving a filter string to a need, most seem to be one-liners.
Sometimes it is required to give more complex filter strings, maybe with one or more *and* or *or* parts.

For readability it is helpful to have this lines as multiline filter strings, but this is not possible if the syntax breaks at the first line.
Maybe this could be fixed cause other options support multiple lines.

Example:
```
.. needtable::
    :style: table
    :filter: id in ['a','b','c','d','e','f','g'] or
             id.startswith("h")

```

**Comment by danwos** [comment]
For complex filter logic, you can use the filter-code or filter-function method.
See: https://sphinx-needs.readthedocs.io/en/latest/filter.html#filter-code

I think this would fulfill your requirements.

**Comment by danwos** [comment]
Good point, the output is not configurable and does not support other languages.

I'm not sure, if this should be given by a directive option or if a variable in `conf.py` may be better.
Maybe we can provide multiple translations, which are selected by the standard sphinx translation solution.
Have to check this.

**Comment by kreuzberger** [comment]
:+1:  https://sphinx-needs.readthedocs.io/en/latest/filter.html#filter-code

**Comment by kreuzberger** [comment]
> Good point, the output is not configurable and does not support other languages.
> 
> I'm not sure, if this should be given by a directive option or if a variable in `conf.py` may be better. Maybe we can provide multiple translations, which are selected by the standard sphinx translation solution. Have to check this.

Is this the right issue? Maybe you have answered #947?
