### ISSUE TITLE
Needflow generated "svg" image contains java logs

### ISSUE THREAD

**Issue by hungdau94** [useblocks/sphinx-needs#950]
Hi all,

I'm trying to use needflow to generate graph for custom needservice objects. ".svg" file is generated in build/html/_images but there are extra java logs which I dont think should be there. Image is fine as long as the extra java logs are removed. 
eAny idea what is causing this issue would be helpful

Here is a list of my dependencies
Sphinx                        7.0.1
sphinx-data-viewer            0.1.2
sphinx-needs                  1.2.2
sphinx-needs-enterprise       1.0.1
sphinx-press-theme            0.8.0
sphinx-rtd-theme              1.1.1
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-plantuml        0.25
sphinxcontrib-programoutput   0.17
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
piccolo-theme                 0.15.0

plantuml-1.2023.10.jar
Redhat openjdk version 1.8.0_372
python 3.11.3

```
[2023-07-24T10:33:43.158] [INFO] ThreadId: 1 ThreadName: main JAVA BRIDGE CONSTRUCTOR.
[2023-07-24T10:33:43.162] [INFO] ThreadId: 1 ThreadName: main os.arch: amd64
[2023-07-24T10:33:43.164] [INFO] ThreadId: 1 ThreadName: main LOADING lib: Microsoft.Flow.RPA.Desktop.UIAutomation.Java.Bridge.Native
[2023-07-24T10:33:43.199] [INFO] ThreadId: 1 ThreadName: main >>> Adding listener.
[2023-07-24T10:33:43.278] [INFO] ThreadId: 19 ThreadName: Thread-4 NamedPipe Server is created
[2023-07-24T10:33:43.282] [INFO] ThreadId: 1 ThreadName: main windows.length: 0
[2023-07-24T10:33:43.284] [INFO] ThreadId: 1 ThreadName: main Java Bridge Initialization completed successfully.
<?xml version="1.0" encoding="us-ascii" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentStyleType="text/css" height="3971px".........
..........................
</g></svg>Dll Process Attached
Dll Process Detach
```

**Comment by danwos** [comment]
Interesting finding. And thanks for reporting.

Sphinx-Needs is using for neeflow generation the sphinxcontrib-plantuml extension, which is using plantuml itself.
This is used the same way as a user would use sphinxcontrib-plantuml, nothing special is added.

So I'm afraid that this may be a bug in sphinxcontrib-plantuml, or I guess even more plantuml itself.
As even sphinxcontrib-plantuml is just calling `java -jar plantuml.jar` as system call from Python and has nothing to do with the Java-part of plantuml itself.

I keep this open for a while, as reminder to make some research here :)

**Comment by hungdau94** [comment]
Thanks for the hint. I googled "plantuml DLL Process attached" and found someone with similar issue.
https://forum.plantuml.net/17523/spurious-java-output-blocking-sphinx

Looks like a rare issue due to libraries used internally by java. I will try installing a different java version

**Comment by hungdau94** [comment]
Image is fine when generating with openjdk 11.0.13

**Comment by danwos** [comment]
Thanks for the research and documenting the solution :+1:
