### ISSUE TITLE
Create reproducible needs.json - remove build timestamp information

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinx-needs#965]
The needs builder does not create [reproducible builds](https://reproducible-builds.org/).
It should, to avoid issues with build caching systems.

Suggested change:

Remove the "created" entry, which contains a build timestamp, from needs.json altogether.

Alternative change:

sphinx HTML build become reproducible when the document does not contain any build time related information (like `Page generated: |today|` or a footer containing the build time formatted according to `html_last_updated_fmt`).

You could add the `created` entry to a needs.json only of `html_last_updated_fmt` is set to None. It being set to `None` is a good indicator that the author of the sphinx project cares for a reproducible documentation build.

You could also just add another `needs_` option, which would make this more explicit. But it's a niche feature, and you already have a very long configuration page and I doubt that there is a person on this planet (except @danwos maybe 😆 ) who remembers all of them.

**Comment by danwos** [comment]
That's an interesting use case and thanks for the proposed solution with `html_last_updated_fmt`.

I'm struggling currently between a new needs config option (I know, another one....) and maybe an extra builder, which removes timestamps.

Using `html_last_updated_fmt` feels a little bit like black voodoo, as the option is not directly related to Sphinx-Needs and a user may not consider that an HTML-related option change will affect the needs.json-output.

I will discuss the different approaches with some users. But for sure in the end, there will be a solution.

**Comment by chrisjsewell** [comment]
> I will discuss the different approaches with some users. But for sure in the end, there will be a solution.

@danwos any update descsion on this? I have no strong feelings either way 😄

**Comment by danwos** [comment]
I would add a new Sphinx-Needs option, maybe just named `needs_reproducible`?
Could be `needs_to_timestamp` as well, but I'm afraid that maybe one day other stuff needs to be removed or an order needs to be kept so that we need a generic option to activate all such kinds of features with one option.

**Comment by arwedus** [comment]
Thanks for tackling this! I agree needs_reproducible_json is a good name. Do you also sort needs in the needs.json and sort the IDs of links and backlinks? Or, put differently - is there any chance that the result of a build of the same input could result in different needs.json files, depending on the order of documents read?

**Comment by chrisjsewell** [comment]
>  Do you also sort needs in the `needs.json`

Yep you beat me to it: the `sort_keys` flag is already set to `true`: https://github.com/useblocks/sphinx-needs/blob/f3725a0cef8c1fac0bafc0f9d7de266974494f6c/sphinx_needs/needsfile.py#L103

> Do you sort the IDs of links and backlinks?

backlinks are not output in the JSON: https://github.com/useblocks/sphinx-needs/blob/40856b2b9cfae042abf0039734680613349f0b6b/sphinx_needs/needsfile.py#L70

links are not sorted as far as I can see

**Comment by arwedus** [comment]
Okay, but links appear in the order the author has given and that cannot change depending on the order of parallel reads, so I guess it's okay.

**Comment by chrisjsewell** [comment]
Yep let me know if you think of anything else non-reproducible, but for now I think we are good
