### ISSUE TITLE
Bug: Sphinx runs full build with "new config" information when a needflow is changed

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinx-needs#971]
## Observed behavior

Whenever I change a needflow diagram (`.. needflow::`), e.g. addition, deletion, or changing a config value (e.g. add "lefttoright"), sphinx rebuilds the project completely, showing `[new config]` after the start.

## Expected behavior

When I change a needflow diagram, only the document that contains the needflow directive is read in again and updated.

**Comment by chrisjsewell** [comment]
I've tested this locally with current master, and don't observe this bug,
nor do I see anything in the latest code to suggest anything to cause this.

So I will close for now, but feel free to re-open if you still observe the issue with v3
